// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © Darth_Buddha

// @version=6
indicator(
      title='Buddha Squeeze',
      shorttitle='Squeeze',
      overlay=false)

//----------------------------------------------------------------------------------------------------< CONSTANTS >---//

const color DARK_GREEN = color.rgb(0, 128, 0)
const color LIGHT_GREEN = color.rgb(0, 255, 0)
const color DARK_RED = color.rgb(128, 0, 0)
const color LIGHT_RED = color.rgb(255, 0, 0)
const color YELLOW = color.rgb(255, 255, 0)
const color BLACK = color.rgb(0, 0, 0)
const color GRAY = color.rgb(120, 120, 120)

//-------------------------------------------------------------------------------------------------------< INPUTS >---//
const string groupSqueeze = 'Squeeze Settings'
const string groupDisplay = 'Display Settings'

i_Length = input.int(21, title='Chart Length', options=[8,13,21,34,55], group=groupSqueeze)
i_StdDevBB = input.float(2.1, title='Bollinger Band StdDev', step=0.1, group=groupSqueeze)
i_StdDevKC = input.float(1.4, title='Keltner Channel StdDev', step=0.1, group=groupSqueeze)

i_TextSize = input.string('large', title='Table Text Size',
  options=['tiny','small','normal','large','huge'], group=groupDisplay)

//----------------------------------------------------------------------------------------------------< FUNCTIONS >---//
// Squeeze detection
method buddhaSqueeze(series float src, int length, float stdKC, float stdBB) =>
    atr = ta.atr(length)
    stdev = ta.stdev(src, length)
    kcWidth = stdKC * atr
    bbWidth = stdBB * stdev
    squeeze = kcWidth != 0 ? (bbWidth / kcWidth) < 1 : false
    squeeze

//-------------------------------------------------------------------------------------------------< CALCULATIONS >---//
// TTM Oscillator
oscBase = (ta.highest(high, i_Length) + ta.lowest(low, i_Length)) / 2 + ta.ema(close, i_Length)
oscillator = ta.linreg(close - oscBase / 2, i_Length, 0)

// Oscillator color
oscillatorColor = oscillator > oscillator[1]
  ? (oscillator > 0 ? DARK_GREEN : LIGHT_GREEN)
  : (oscillator > 0 ? LIGHT_RED : DARK_RED)

// Pseudo‑code snippet for regime‑based stdDevBB
volRegime = ta.atr(i_Length) > ta.ema(ta.atr(i_Length), 50) ? high : low
bbMult = volRegime == high ? 2.2 : 1.8
kcMult = volRegime == high ? 1.7 : 1.3
squeezeSignal = buddhaSqueeze(close, i_Length, kcMult, bbMult)

// Squeeze Signal
//squeezeSignal = buddhaSqueeze(close, i_Length, i_StdDevKC, i_StdDevBB)

// Squeeze Length Counter
var int squeezeCount = na
squeezeCount := squeezeSignal ? (nz(squeezeCount) + 1) : 0

// Label Texts
squeezeLabelText = squeezeCount > 0 ? ' S ' : '   '
squeezeSignalCount = squeezeCount > 0 ? str.tostring(squeezeCount) : na

//-------------------------------------------------------------------------------------------------------< VISUAL >---//
// Zero Line
hline(0,
  title = 'Zero Line',
  color = color.rgb(255,255,255,70),
  linestyle = hline.style_solid)

// Oscillator Bars
plot(oscillator * 100,
  title = 'TTM',
  color = oscillatorColor,
  style = plot.style_columns)

// Squeeze Circles
plot(0,
  title = 'Squeeze',
  color = squeezeSignal ? YELLOW : na, linewidth = 2,
  style = plot.style_steplinebr,
  display = display.pane)

//-------------------------------------------------------------------------------------------------------< TABLES >---//
// Table Style
var table squeezeTable = table.new(position.middle_right, columns=1, rows=2)

if barstate.islast
    table.cell(
      table_id = squeezeTable,
      column = 0, row = 0,
      text = 'S', text_color = BLACK, text_size = i_TextSize,
      bgcolor = squeezeSignal ? YELLOW : GRAY,
      text_formatting = text.format_bold)
    table.cell(
      table_id = squeezeTable,
      column = 0, row = 1,
      text = squeezeSignalCount, text_color = BLACK, text_size = i_TextSize,
      bgcolor = oscillatorColor,
      text_formatting = text.format_bold)

// Table Style
table.set_bgcolor(squeezeTable, BLACK)
table.set_frame_color(squeezeTable, BLACK)
table.set_border_color(squeezeTable, BLACK)
table.set_frame_width(squeezeTable, 3)
table.set_border_width(squeezeTable, 5)

//-----------------------------------------------------------------------------------------------------< END CODE >---//